### ISSUE TITLE
JS Party #287 — Val Town’s use of “were” is correct

### ISSUE THREAD

**Issue by brycewray** [thechangelog/show-notes#235]
I no longer use any of the other social media platforms you folks inhabit, so I have to mention this here.

I’m listening to JS Party #287, “Take me to Val Town.” About two-and-a-half minutes into the episode, [Amal](https://github.com/nomadtechie) teased Val Town’s [Steve Krouse](https://github.com/stevekrouse) about the use of “were” next to a singular item (“AWS Lambda”) in the Val Town website’s headline. **However**, Val Town is **correct** in using “were” in this case because it’s an “[unreal conditional](https://www.grammarly.com/blog/conditional-sentences-was-instead-of-were/).”

For example: if I go outside on an extremely hot day and walk barefooted on the sidewalk, I could correctly say, “If this sidewalk were air-conditioned, my feet wouldn’t be hurting right now.”

**Comment by jerodsanto** [comment]
@brycewray _unreal_ correction, thanks for putting Amal in her place 😎 

We do have [commenting on the website](https://changelog.com/news/take-me-to-val-town-2lG7), which will ensure everyone on the episode gets notified of what you have to say. Just go to the episode page and click "Discuss" in the play bar under the title (direct link in show notes):

<img width="1624" alt="Screenshot 2023-08-12 at 8 04 32 AM" src="https://github.com/thechangelog/show-notes/assets/8212/edb9c788-6287-4730-bfde-f0086ec1a19d">

I'd suggest using that instead of this repo for future mentions. ✊
